#!/bin/bash
# Build enhancer
set -e
cd "$(realpath -m "$0/../..")/enhancer"


# Clear existing
rm -rf dist


# Build css
npx sass --style=compressed --embed-sources src/styles.sass dist/styles.css


# Common args
esbuild="npx esbuild --target=ES2019 --platform=browser"


# Build ESM with typings
npx tsc --emitDeclarationOnly --outDir dist/esm
$esbuild src/*.ts --sourcemap --format=esm --outdir=dist/esm


# Build auto-executing version
$esbuild execute.ts --bundle --minify --loader:.css=text --outfile=dist/execute.js
