#!/bin/bash
# Execute collector within the test collection
set -e
cd "$(realpath -m "$0/../..")/collection"


../.bin/build_collector --log-level=warning
NODE_OPTIONS="--no-warnings" node ../collector/dist/index.js "$@"
