#!/bin/bash
# Execute collector within the alternate test collection
set -e
cd "$(realpath -m "$0/../..")/collection_alt"


../.bin/build_collector --log-level=warning
NODE_OPTIONS="--no-warnings" node ../collector/dist/index.js "$@"
