#!/bin/bash
# Publish collector
set -e
cd "$(realpath -m "$0/../..")/collector"


../.bin/build_collector

# Also include types (slow so not part of build command)
npx tsc --emitDeclarationOnly --outDir dist

npm publish --access=public
