#!/bin/bash
# Publish app
set -e
cd "$(dirname "$(dirname "$0")")/app"

# Do fresh build of components app relies on since they're bundled when published
../.bin/build_references
../.bin/build_client

../.bin/build_app

# Publish to server
npx esbuild --platform=node ../.bin/publish.ts | node --input-type=module

# Publish to npm
npm publish --access=public
