#!/bin/bash
# Wipe and rebuild test collection
set -e
set -x
cd "$(realpath -m "$0/../..")"

# Wipe collection
rm -rf collection
mkdir collection

# Rebuild collector
.bin/build_collector

# Build collection from scratch
.bin/collector setup
.bin/collector discover ebible engbsb
.bin/collector discover dbl 5cc7093967a0a392
.bin/collector download eng_bsb
.bin/collector download vie_bib
.bin/collector process
.bin/collector glosses
.bin/collector notes
.bin/collector crossref
.bin/collector manifest
