#!/bin/bash
# Wipe and rebuild test collection
set -e
set -x
cd "$(realpath -m "$0/../..")"

# Wipe collection
rm -rf collection
mkdir collection

# Rebuild collector
.bin/build_collector

# Build collection from scratch
.bin/collector setup
.bin/collector discover ebible eng_bsb
.bin/collector discover dbl vie_ovcb
.bin/collector download eng_bsb
.bin/collector download vie_ovcb
.bin/collector process
.bin/collector notes-process
.bin/collector data-crossref
